- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Start and enable Nginx
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: Copy index.html with IP address
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html

- name: Install CloudWatch Agent
  shell: |
    sudo yum install -y amazon-cloudwatch-agent
    sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
      -a fetch-config -m ec2 -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json -s